
#comando para remover pastas
RMDIR = rm -rf
#comando para remover arquivos
RM = rm -f
CD = cd
#comando para executar o make
MAKE = make


FLAGS= -Wall -pedantic -Wextra
DFLAGS = -ggdb -O0



#Arquivos que devem ser compilados:
C_FILES= $(wildcard ./170052427/*.c)
FLEX_FILES= $(wildcard ./170052427/*.l)


#Nome do executável
EXEC = exec


all: $(EXEC)

$(EXEC): $(FILES)
  flex $(FLEX_FILES)
	gcc $(C_FILES) $(FLAGS)

debug: FLAGS += $(DFLAGS)
debug: all

clean:
	$(RM) $(EXEC)
  $(RM) lex.yy.c


again: clean
again: all

first: chmod 777 -R ./170052427/
first: all


help:
	@echo.
	@echo Available targets:
	@echo - all:      Builds the release version (default target)
  @echo - first:    Gives permission at the first time (or when added new files)
	@echo - debug:    Builds the debug version
	@echo - clean:    Clean compilation files and executable
	@echo - help:     Shows this help
	@echo.

